### ISSUE TITLE
Launch prep checklist

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-sfpublicpress#151]
- [x] Reduce TTL times as much as possible
- [x] Triple check we have all the access we need
   - [x] domain registrar
   - [x] drupal
   - [x] cpanel
   - [x] WHM
- [x] Plan for archive site
- [x] Finalize launch checklist
- [x] Compile a list of 10-20 random URLs from the old site to test redirects right after launch
- [x] Confirm hosting questions
- [x] Confirm Michael as point of contact and timeline for launch
